# Lesson 1.6: Introduction to NumPy

## Introduction
**NumPy**, short for Numerical Python, is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

Many computational and data science packages use NumPy as the main building block. It is a fundamental library for scientific computing in Python.

### Key Features of NumPy:
* **ndarray**: An efficient multidimensional array providing fast array-oriented arithmetic operations and flexible broadcasting capabilities.
* **Vectorization**: Mathematical functions for fast operations on entire arrays of data without having to write loops.
* **Linear Algebra**: Tools for random number generation, Fourier transforms, and matrix manipulation.
* **C API**: For connecting NumPy with libraries written in C, C++, or FORTRAN.

### Advantages over Python Lists:
1. **Contiguous Memory**: NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects. This allows for significantly faster access and manipulation.
2. **Vectorized Operations**: NumPy algorithms written in C can operate on this memory without type checking or other Python overhead, performing complex computations without slow `for` loops.

![numpy_vs_list](https://github.com/soloestoydx/6m-data-1.6-intro-numpy/blob/main/assets/numpy_vs_python_list.png?raw=1)

## Part 1: Performance Benchmark
To give you an idea of the performance difference, consider a NumPy array of one million integers and an equivalent Python list. We use the `%timeit` magic command to measure execution time.

In [1]:
import numpy as np  # standard alias for numpy, always import package this way

my_arr = np.arange(1_000_000)  # numpy array holding integers 0 to 999,999, np.arange() is a vectorized function that creates an array of evenly spaced values, similar to Python's built-in range() function but returns a numpy array instead of a list

my_list = list(range(1_000_000))  # plain python list, same values, list() is a built-in function that creates a list from an iterable, in this case the range object returned by range()

print("NumPy Vectorized Multiplication (my_arr * 2):")
%timeit my_arr2 = my_arr * 2  # numpy multiplies every element at once, no loop needed

print("\nPython List Comprehension ([x * 2 for x in my_list]):")
%timeit my_list2 = [x * 2 for x in my_list]  # python must loop over each item one by one

NumPy Vectorized Multiplication (my_arr * 2):
1.5 ms ± 429 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

Python List Comprehension ([x * 2 for x in my_list]):
64.3 ms ± 13.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Part 2: The ndarray (N-dimensional array)
The `ndarray` is a fast, flexible container for large datasets. It is a multidimensional array of fixed size with **homogeneous** elements (all elements must be of the same type).

### ndarray illustration
![ndarray](https://github.com/soloestoydx/6m-data-1.6-intro-numpy/blob/main/assets/numpy_ndarray.png?raw=1)

### 1D Array
`shape = (N,)`
Only：**axis 0**
1-dimensional array, vector

### 2D Array
`shape = (rows, columns)`
- axis 0 → **row**
- axis 1 → **column**

### 3D Array
`shape = (slices / planes, row, column)`
- axis 0：**slice / plane**
- axis 1：**row**
- axis 2：**column**

A 3D array consists of multiple **2D planes (slices)** stacked together.

---
### Comparison Table of Dimensions
| Dimension | shape | axis0 | axis1 | axis2 |
|------|----------|-------|-------|-------|
| 1D | (X,) | elements | — | — |
| 2D | (R,C) | row | column | — |
| 3D | (S,R,C) | slice/plane | row | column |
---

### 4D Array
`shape = (batch, height, width, channel)` → 4D, grayscale or color images with multiple channels (e.g., RGB)

### More than 4 dimensions: General Rules (Arbitrary High-dimensional NumPy)
As the number of dimensions increases, the intuitive terms like "row" and "column" are no longer applicable. Instead, we refer to them uniformly as:
**axis 0, axis 1, axis 2, axis 3 …**
This is also the preferred terminology used in the official NumPy documentation.

Every array has:
* **shape**: A tuple indicating the size of each dimension.
* **dtype**: An object describing the data type of the array.
* **ndim**: The number of dimensions (axes).

These are the three most important **attributes** of a NumPy array.



In [2]:
# [DEMO] Creating arrays from sequences
data1 = [6, 7.5, 8, 0, 1]  # a normal python list of numbers
arr1 = np.array(data1)  # np.array() converts a list into a numpy array

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]  # a list of lists = 2 rows, 4 columns
arr2 = np.array(data2)  # becomes a 2D array (a grid/table of numbers)

print(f"Array 2:\n{arr2}")
print(f"\nShape: {arr2.shape}, \nDtype: {arr2.dtype}, \nDimensions: {arr2.ndim}")
# shape = (rows, columns), dtype = data type stored, ndim = number of dimensions, these are all attributes of a numpy array object, accessed with dot notation

Array 2:
[[1 2 3 4]
 [5 6 7 8]]

Shape: (2, 4), 
Dtype: int64, 
Dimensions: 2


### Data Types and Casting
NumPy supports specific numerical types like `int32`, `float64`, etc. You can explicitly convert an array from one `dtype` to another using the `astype` method.

**Note:** If you cast floating-point numbers to an integer `dtype`, the decimal part will be truncated.

In [3]:
# [DEMO] Casting arrays
arr = np.array([3.7, -1.2, 0.5, 12.9])  # array of decimal (float) numbers

print("Original:", arr)

print("Casted to int32:", arr.astype(np.int32))  # astype() converts dtype; decimals get cut off (not rounded)

Original: [ 3.7 -1.2  0.5 12.9]
Casted to int32: [ 3 -1  0 12]


### 👋 Exercise 1: Creation & Casting
1. Create a 3x4 array of all ones using `np.ones()`.
2. Cast this array to `float32`.
3. Create an array of strings representing numbers: `['1.25', '-9.6', '42']`. Cast it to `float`.

In [4]:
# 3×4 array of ones
arr = np.ones((3, 4))
print(arr, arr.shape, arr.dtype)  # (3, 4) float64

# Cast to float32 (half the memory)
arr_f32 = arr.astype(np.float32)
print(arr_f32.dtype)  # float32

# String array cast to float
string_nums = np.array(['1.25', '-9.6', '42'])
floats = string_nums.astype(float)
print(floats)


(3, 4) float64
float32
[ 1.25 -9.6  42.  ]


## Part 3: Arithmetic & Broadcasting
Arithmetic operations are applied as batch operations without for loops.

**Broadcasting** describes how arithmetic works between arrays of different shapes.

![vectorization](https://github.com/soloestoydx/6m-data-1.6-intro-numpy/blob/main/assets/vectorization.png?raw=1)

Example: A scalar value being replicated (broadcast) to match the shape of a larger array.

In [5]:
# [DEMO] Arithmetic & Broadcasting
arr = np.array([[1., 2., 3.], [4., 5., 6.]])  # 2D array, 2 rows x 3 columns

print("Original array:\n", arr)

print("\nElement-wise multiplication (arr * arr):\n", arr * arr)  # each number multiplied by itself, position by position

print("\nBroadcasting scalar (arr + 10):\n", arr + 10)  # 10 is "stretched" to match arr's shape, then added to every element

print("\nBroadcasting scalar (1 / arr):\n", 1 / arr)  # single number 1 applied to every element automatically

Original array:
 [[1. 2. 3.]
 [4. 5. 6.]]

Element-wise multiplication (arr * arr):
 [[ 1.  4.  9.]
 [16. 25. 36.]]

Broadcasting scalar (arr + 10):
 [[11. 12. 13.]
 [14. 15. 16.]]

Broadcasting scalar (1 / arr):
 [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


## Part 4: Indexing and Slicing
One-dimensional arrays act similarly to Python lists. In 2D arrays, indexing can be done with `[row, column]` syntax.

### Slicing syntax cheat sheet
Basic slice form: `start:stop:step` (any part can be left out).

* `arr[i]` \- single element at index `i`.
* `arr[start:stop]` \- elements from `start` up to (not including) `stop`.
* `arr[:stop]` \- from the beginning up to `stop`.
* `arr[start:]` \- from `start` to the end.
* `arr[:]` \- everything (a full copy of the view, same data).
* `arr[start:stop:step]` \- every `step`-th element between `start` and `stop`.
* `arr[::-1]` \- reverses the array (step of `-1`).
* Negative indices count from the end: `arr[-1]` is the last element, `arr[-2]` the second-to-last.

For 2D arrays, combine two slices separated by a comma: `arr2d[row_slice, col_slice]`.

* `arr2d[i, j]` \- single element at row `i`, column `j`.
* `arr2d[i]` or `arr2d[i, :]` \- entire row `i` (returned as a 1D array).
* `arr2d[:, j]` \- entire column `j` (returned as a 1D array).
* `arr2d[:2, 1:]` \- rows 0-1 (`:2` means "up to index 2"), columns 1 onwards (`1:` means "from index 1").

### 2D Array Indexing Syntax
![2d_array_indexing](https://github.com/soloestoydx/6m-data-1.6-intro-numpy/blob/main/assets/ndarray_axis_index.png?raw=1)

**Important:** Array slices are **views** on the original array. This means data is not copied, and modifications to the slice will be reflected in the source array.

In [6]:
# [Demo] Slicing patterns
arr = np.arange(10)  # array: 0,1,2,...,9
print("arr:", arr)

print("\narr[2:5]   (index 2 up to 5):", arr[2:5])       # elements at index 2,3,4 - stop index NOT included
print("arr[:4]    (start to index 4):", arr[:4])         # elements at index 0,1,2,3
print("arr[6:]    (index 6 to end):  ", arr[6:])         # elements at index 6,7,8,9
print("arr[::2]   (every 2nd item):  ", arr[::2])        # step of 2 - skips every other element
print("arr[::-1]  (reversed):        ", arr[::-1])       # step of -1 - walks backwards through array
print("arr[-3:]   (last 3 items):    ", arr[-3:])        # negative index counts from the end

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # 3x3 grid
print("\narr2d:\n", arr2d)
print("\narr2d[1]     (row 1 only):        ", arr2d[1])        # single row -> returned as 1D array
print("arr2d[:, 0]  (column 0 only):     ", arr2d[:, 0])       # single column -> returned as 1D array
print("arr2d[1, 2]  (row 1, col 2):      ", arr2d[1, 2])       # single element
print("arr2d[::-1]  (rows reversed):\n", arr2d[::-1])          # reverses row order, columns unchanged

arr: [0 1 2 3 4 5 6 7 8 9]

arr[2:5]   (index 2 up to 5): [2 3 4]
arr[:4]    (start to index 4): [0 1 2 3]
arr[6:]    (index 6 to end):   [6 7 8 9]
arr[::2]   (every 2nd item):   [0 2 4 6 8]
arr[::-1]  (reversed):         [9 8 7 6 5 4 3 2 1 0]
arr[-3:]   (last 3 items):     [7 8 9]

arr2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

arr2d[1]     (row 1 only):         [4 5 6]
arr2d[:, 0]  (column 0 only):      [1 4 7]
arr2d[1, 2]  (row 1, col 2):       6
arr2d[::-1]  (rows reversed):
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


### 👋👋👋 Group Exercise 2: The Logic of Slicing
1. Select the first column of `arr2d` using a slice.
2. Set all values in the second row to 0.
3. **Socratic Prompt:** How does `arr2d[1]` differ from `arr2d[1, :]`? (Hint: check shapes)

In [ ]:
# Your code here
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[:,0]
arr2d[1] = 0



## Part 5: Boolean Indexing
Like arithmetic operations, comparisons (such as `==`) with arrays are vectorized. This yields a boolean array which can be used to filter data.

In [7]:
# [DEMO] Filtering scores
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  # array of names
scores = np.array([[75, 80], [85, 90], [95, 100], [100, 77], [85, 92], [95, 80], [72, 80]])  # each row = one person's scores

bob_mask = (names == 'Bob')  # bool array: True where name is 'Bob', False elsewhere

print("Bob Mask:", bob_mask)
print("\nBob's scores:\n", scores[bob_mask])  # using bool array to keep only matching rows

Bob Mask: [ True False False  True False False False]

Bob's scores:
 [[ 75  80]
 [100  77]]


### 👋👋👋 Group Exercise 3: Complex Filtering
1. Select all scores where the name is NOT 'Bob'.
2. Select scores for 'Bob' or 'Will' using the `|` operator.
3. Find all scores less than 80 and set them to 0.

In [8]:
# Your code here
# 1. Scores where name is NOT 'Bob'
print(scores[names != 'Bob'])

# 2. Scores for 'Bob' or 'Will'
mask = (names == 'Bob') | (names == 'Will')
print(scores[mask])

# 3. Set all scores below 80 to 0 — this modifies the array in place
scores[scores < 80] = 0
print(scores)


[[ 85  90]
 [ 95 100]
 [ 85  92]
 [ 95  80]
 [ 72  80]]
[[ 75  80]
 [ 95 100]
 [100  77]
 [ 85  92]]
[[  0  80]
 [ 85  90]
 [ 95 100]
 [100   0]
 [ 85  92]
 [ 95  80]
 [  0  80]]


## Part 6: Universal Functions (ufuncs) and Methods
A **ufunc** is a function that performs element-wise operations on data in ndarrays.

* **Unary ufuncs**: Take one array (e.g., `sqrt`, `exp`).
* **Binary ufuncs**: Take two arrays (e.g., `add`, `maximum`).
* **Statistical Methods**: `mean`, `sum`, `std` can be computed over the entire array or along an axis.

In [9]:
# [DEMO] Statistical Methods
arr = np.random.randn(3, 4)  # random 3x4 array, values from normal distribution

print("Random Array:\n", arr)
print("\nMean down rows (axis=0):", arr.mean(axis=0))  # axis=0 collapses rows, giving one value per column
print("\nSum across columns (axis=1):", arr.sum(axis=1))  # axis=1 collapses columns, giving one value per row

Random Array:
 [[-0.74499475  0.14415053  0.1504431  -2.13415127]
 [-2.56312588  0.40489275  1.164088   -1.05780955]
 [-0.45552235 -1.86022672  0.79537217 -1.48283802]]

Mean down rows (axis=0): [-1.25454766 -0.43706115  0.70330109 -1.55826628]

Sum across columns (axis=1): [-2.58455239 -2.05195467 -3.00321492]


## Part 7: Linear Algebra
Linear algebra operations, like matrix multiplication, are crucial for many data science algorithms. Multiplying two arrays with `*` is an element-wise product; for matrix multiplication, use `.dot()` or the `@` operator.

### Matrix multiplication, no linear algebra background needed
Shapes must "match in the middle": `(m, n) @ (n, p)` gives you `(m, p)`. Below, a 2x3 matrix times a 3x2 matrix gives a 2x2 result - the two 3's cancel out.

```
x (2x3)          y (3x2)          result (2x2)
[1 2 3]          [6   23]
[4 5 6]    @     [-1   7]    =    [? ?]
                 [8    9]         [? ?]
```

To get each number in the result, take a **row** from `x` and a **column** from `y`, multiply them element-by-element, then add up the products (this is called the "dot product"):

* result row 0, col 0 = `1*6 + 2*(-1) + 3*8` = `6 - 2 + 24` = `28`
* result row 0, col 1 = `1*23 + 2*7 + 3*9` = `23 + 14 + 27` = `64`
* result row 1, col 0 = `4*6 + 5*(-1) + 6*8` = `24 - 5 + 48` = `67`
* result row 1, col 1 = `4*23 + 5*7 + 6*9` = `92 + 35 + 54` = `181`

So `x @ y` = `[[28, 64], [67, 181]]` - row count comes from `x`, column count comes from `y`.

![matrix_multiplication](https://github.com/soloestoydx/6m-data-1.6-intro-numpy/blob/main/assets/matrix_multiplication.png?raw=1)

In [ ]:
# [DEMO] Matrix Multiplication
x = np.array([[1, 2, 3], [4, 5, 6]])  # 2x3 matrix
y = np.array([[6, 23], [-1, 7], [8, 9]])  # 3x2 matrix

print("Matrix product (x @ y):\n", x @ y)  # @ does real matrix multiplication (rows times columns), different from x * y

print("\nnp.dot(x, y):\n", np.dot(x, y))  # np.dot() does the same thing as @ operator

### 👋 Exercise 4: Reshaping & Statistics
1. Create an array of 15 integers using `arange(15)` and reshape it to `(3, 5)`.
2. Calculate the average value of each row.
3. Use `np.unique()` to find distinct elements in an array of your choice.
4. Transpose the reshaped array using `.T` and check the new shape.

In [ ]:
# Your code here
